############# English navigation ##############

# main menu
[[main]]
name = "Services"
weight = 1
hasChildren = true

[[main]]
parent = "Services"
name = "Revenue Analytics"
url = "/services/revenue-analytics"
weight = 1

[[main]]
parent = "Services"
name = "Data Foundation"
url = "/services/data-foundation"
weight = 2

[[main]]
parent = "Services"
name = "Data Activation"
url = "/services/data-activation"
weight = 3

[[main]]
name = "About"
url = "/about"
weight = 2

[[main]]
name = "Blog"
url = "/blog"
weight = 3


# footer menu
[[footer]]
name = "Services"
url = "/services/revenue-analytics"
weight = 1

[[footer]]
name = "About"
url = "/about"
weight = 2

[[footer]]
name = "Blog"
url = "/blog"
weight = 3

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 4

[[footer]]
name = "Terms of Service"
url = "/terms"
weight = 5
